type = "ingredient"
name = "bread flour"
author = "sudo-nano"
lastUpdated = "2025-11-06"

unitType = "mass"

# Density: 120g / cup according to King Arthur flour, 0.5-0.6 g/mL according to Wikipedia
# https://en.wikipedia.org/wiki/Cup_(unit)#Dry_measure
density.amount = 0.55
density.unit = "g/mL"

[restrictions.dietary]
animalProduct = false
meat = false
egg = false
dairy = false
gluten = true
treeNuts = false
sesame = false
shellfish = false

[restrictions.religious]
halal = true
kosher = true
leavened = false

# TODO: add purchase increments
