type = "ingredient"
name = "sesame oil"
author = "sudo-nano"
lastUpdated = "2025-11-10"

unitType = "volume"
# TODO: Look up density 

[restrictions.dietary]
animalProduct = false
meat = false
egg = false 
dairy = false 
gluten = false 
treeNuts = false
sesame = true
shellfish = false

[restrictions.religious]
halal = true
kosher = true
leavened = false

[purchase_increments]
increments = [
	[5.0, "L", 40.00]
]
